# page no 24
conclusion <- c("Effective", "Not effective")
controls <- c(rep("Randomized", 8), rep("Historical", 21))
n_studies <- c(1, 7, 16, 5)
data <- data.frame(Conclusion = rep(conclusion, 2), Controls = controls, N_Studies = n_studies)
chi_square_result <- chisq.test(matrix(data$N_Studies, nrow = 2), correct = FALSE)
print("Chi-square test for independence:")
print(chi_square_result)
data$Proportion <- data$N_Studies / sum(data$N_Studies)
print(data)
