#Page no. 7.59
rm(list=ls(all=T))
Ni<-c(394,461,391,334,169,113,148)
N<-sum(Ni)
n<-150
Y_bar_Ni<-c(5.4,16.3,24.3,34.5,42.1,50.1,63.8)
Si<-c(8.3,13.3,15.1,19.8,24.5,26,35.2)
Y_bar_N<-round(sum(Ni*Y_bar_Ni)/N,digits=4)
Y_bar_N
S_sq<-(sum((Ni-1)*Si^2)+sum(Ni*Y_bar_Ni^2)-N*Y_bar_N^2)/(N-1)
S_sq
Var_y_bar_n_R<-round(((N-n)/(N*n))*S_sq,digits=4)
Var_y_bar_n_R
Var_Y_est_R<-(N^2)*Var_y_bar_n_R
Var_Y_est_R
Var_Y_est_P<-((N-n)/n)*sum(Ni*Si^2)
Var_Y_est_P
Var_y_bar_st_N<-(((sum(Ni*Si))^2)/(n*N^2))-((sum(Ni*Si^2))/N^2)
Var_Y_est_Ney<-N^2*Var_y_bar_st_N
Var_Y_est_Ney
Var_y_bar_st_P<-round(Var_Y_est_P/N^2,digits=4)
Var_y_bar_st_P
Var_y_bar_st_Ney<-round(Var_y_bar_st_N,digits=4)
Var_y_bar_st_Ney
eff_prop_alloc<-((Var_y_bar_n_R)-(Var_y_bar_st_P))/Var_y_bar_st_P
eff_prop_alloc
eff_Ney_alloc<-(Var_y_bar_n_R-(Var_y_bar_st_Ney))/Var_y_bar_st_Ney
eff_Ney_alloc