###page_no_620###
rm(list=ls())
x<-c(1,2,3,4,5,6)
y<-c(6,1,9,5,17,12)
n=6
sum(x)
sum(y)
sum(x*y)
sum(x^2)
s_xy<-(sum(x*y)-((sum(x)*sum(y))/n))/(n-1);s_xy
var(x)
b1<-s_xy/var(x);b1
mean(x)
mean(y)
b0<-mean(y)-b1*mean(x);b0
est_y<-b0+b1*x;est_y
e<-y-est_y;e
sum(e^2)
plot(x,y,type="p")
abline(lm(y~x))