# page no : 140
library(prob)
library(MASS)
coin=tosscoin(2)
A=subset(coin,toss1=="H" | toss2=="H")
P_A=nrow(A)/nrow(coin)
print(paste("The event of getting at most one tail P(A)=",fractions(P_A)))
B=subset(coin,toss1=="T" & toss2=="T")
P_B=1-P_A
print(paste("The event of getting all tail P(B) =",fractions(P_B)))
C=subset(coin,toss1=="H" & toss2=="H")
P_C=nrow(C)/nrow(coin)
print(paste("The event of getting all heads P(B int C)=",fractions(P_C)))
BintC=intersect(B,C)
P_BintC=nrow(BintC)/nrow(coin)
D=subset(coin,toss1=="T" & toss2=="T")
P_D=nrow(D)/nrow(coin)
print(paste("The event of getting more than one tail in both coin P(D)=",fractions(P_D)))
E=subset(coin,toss1=="H" & (toss1=="H"|toss2=="T"))
P_E=nrow(E)/nrow(coin)
print(paste("The event of getting a head on the first roll P(E)=",fractions(P_E)))
F=subset(coin,toss1=="T" |toss2=="T")
P_F=nrow(F)/nrow(coin)
print(paste("The event of getting a head on the first roll P(F) =",fractions(P_F)))