#page no:160-161
library(data.tree)
library("prob")
library("dplyr")
library("MASS")
x<-Node$new(" ")
    firstdraw_blue<-x$AddChild("B \n 8/11")
       seconddraw_blue<-firstdraw_blue$AddChild("B \n 7/10")
       seconddraw_red<-firstdraw_blue$AddChild("R \n 3/10")
           thirddraw_blue<-seconddraw_blue$AddChild("56/110 \n BB")
           thirddraw_red<-seconddraw_red$AddChild("24/110 \n BR")
    firstdraw_red<-x$AddChild("R \n 3/11")
       seconddraw_blue<-firstdraw_red$AddChild("B \n 8/10")
       seconddraw_red<-firstdraw_red$AddChild("R \n 2/10")
            thirddraw_blue<-seconddraw_blue$AddChild("24/110 \n RB")
            thirddraw_red<-seconddraw_red$AddChild("6/110 \n RR")

print(x)
plot(x)
P_RR=(3/11)*(2/10)
print(paste("a. the solution is P(RR) =",fractions(P_RR)))
P_RB_U_BR=((3/11)*(8/10))+((8/11)*(3/10))
print(paste("b. the solution  is P(RR U BR)=",fractions(P_RB_U_BR)))
P_R2_int_B1=(3/10)
print(paste("c.the solution  is P(R on 2nd | B on 1st)=",fractions(P_R2_int_B1)))
P_R1_int_B2=(3/11)*(8/10)
print(paste("d.the solution  is P(R on 1st n B on 2nd)=",fractions(P_R1_int_B2)))
P_BB=(8/11)*(7/10)
print(paste("e.the solution  is P(BB)=",fractions(P_BB)))
P_B2_int_R1=(8/10)
print(paste("f. the solution  is P(B on 2nd | R on 1st)=",fractions(P_B2_int_R1)))