#pageno 162-163
library(data.tree)
library("prob")
library("dplyr")
library("MASS")
x<-Node$new(" ")
    firstdraw_blue<-x$AddChild("T \n 4/9")
       seconddraw_blue<-firstdraw_blue$AddChild("T \n 3/8")
       seconddraw_red<-firstdraw_blue$AddChild("B \n 5/8")
           thirddraw_blue<-seconddraw_blue$AddChild("TT")
           thirddraw_red<-seconddraw_red$AddChild("TB")
    firstdraw_red<-x$AddChild("B \n 5/9")
       seconddraw_blue<-firstdraw_red$AddChild("T \n 4/8")
       seconddraw_red<-firstdraw_red$AddChild("B \n 4/8")
            thirddraw_blue<-seconddraw_blue$AddChild("BT")
            thirddraw_red<-seconddraw_red$AddChild("BB")
print(x)
plot(x)
P_TT=(4/9)*(3/8)
print(paste("a.the probability both kittens are tabby is option C =",fractions(P_TT)))
P_T_B=((4/9)*(5/8))+((5/9)*(4/8))
print(paste("b.the probability one kitten of each color is option d =",fractions(P_T_B)))
P_B_T=(4/8)
print(paste("c.the probability tabby second and black first is =",fractions(P_B_T)))
P_TT_BB=((4/9)*(3/8))+((5/9)*(4/8))
print(paste("d.the probability both kittens are same color is =",fractions(P_TT_BB)))