#pg.no.572 
n=15
xbar=7.2
sxx=33.6
sxy=-57.2
ybar=45.6
syy=160.2
beta1_cap=(sxy/sxx)
beta0_cap=(ybar-(beta1_cap*xbar))
beta0_cap
b=beta1_cap
ycap=substitute(expresion(a+(b*x)),list(a=beta0_cap,b=beta1_cap))
alpha=.01 
df=n-2
t_0.01=qt(alpha,df)
t_0.01
SEE=(syy-(sxy^2/sxx))
s=sqrt(SEE/(n-2))
s
s_e_beta1_cap=(s/sqrt(sxx))
s_e_beta1_cap
t_cal=beta1_cap/s_e_beta1_cap
alpha_95=0.05/2
xstar=9
est_mean=beta0_cap+(beta1_cap*xstar)
est_sd=s*(sqrt((1/n)+(((xstar-xbar)^2)/sxx)))
conf_int=(est_mean+(c(qt(alpha_95,df),-qt(alpha_95,df))*est_sd))
y_35_cap=beta0_cap+(b=beta1_cap*35)
ycap 
t_cal
list(estimated_mean=est_mean,confidence_interval=conf_int) 
y_35_cap 