# Page Number : 171
vol  =  1
na = 2;
nb = 3;
nc = 4;
mma = 2;
mmb = 3;
mmc = 4;
ma = na*mma;
mb = nb*mmb;
mc = nc*mmc;
NabyA = 2+2;
NbbyA = -1+3;
NcbyA = 0+4;
NtbyA = NabyA+NbbyA+NcbyA;
nabyA = 4+4;
nbbyA = -3+9;
ncbyA = 0+16;
CA = na/vol;
CB = nb/vol;
CC = nc/vol;
CT = CA+CB+CC;
pa = ma/vol;
pb = mb/vol;
pc = mc/vol;
Ua = NabyA/CA;
Ub = NbbyA/CB;
Uc = NcbyA/CC;
U = (pa*Ua+pb*Ub+pc*Uc)/(pa+pb+pc);
Ustar = (NtbyA/CT);
JabyA = CA*(Ua-U);
JbbyA = CB*(Ub-U);
JcbyA = CC*(Uc-U);
print(JabyA);
print(JbbyA);
print(JcbyA);
jabyA = pa*(Ua-U);
jbbyA = pb*(Ub-U);
jcbyA = pc*(Uc-U);
print(jabyA);
print(jbbyA);
print(jcbyA);
JastarbyA = CA*(Ua-Ustar);
JbstarbyA = CB*(Ub-Ustar);
JcstarbyA = CC*(Uc-Ustar);
print(JastarbyA);
print(JbstarbyA);
print(JcstarbyA);
jastarbyA = pa*(Ua-Ustar);
jbstarbyA = pb*(Ub-Ustar);
jcstarbyA = pc*(Uc-Ustar);
print(jastarbyA);
print(jbstarbyA);
print(jcstarbyA);
