#page no. 3.15
rm(list=ls(all=T))
w<-c(30,15,20,10,25)
po<-c(100,20,70,20,40)
pi<-c(90,20,60,15,55)
Groups<-c("Food","Rent","Clothing","Fuel","Others")
P<-round((pi/po)*100,digits=1)
wP<-w*P
logP<-round(log10(P),digits=4)
wlogP<-round(w*logP,digits=3)
df<-data.frame(Groups,w,po,pi,P,wP,logP,wlogP,stringsAsFactors=F)
computation<-rbind(df,c('Total',"","","","",sum(wP),"",sum(wlogP)))
computation
#Part(i)
Poi_AM<-(sum(wP)/sum(w))
Poi_AM
#Part(ii)
Poi_GM<-round(10^(sum(wlogP)/sum(w)),digits=2)
Poi_GM