# Page No :  45
V = 24;
Rab = 13;
Rbc = 11;
Rbe = 18;
Rce = 14;
Red = 9;
Rcd = 5;
Rae = 22;
Rx = Rae;
Ry = Rbe;
Raf = 1;
Rce = ((Rcd+Red)*(Rce))/(Rcd+Red+Rce);
Rbe = ((Rbc+Rce)*(Rbe))/(Rbc+Rce+Rbe);
Rae = ((Rab+Rbe)*(Rae))/(Rab+Rbe+Rae);
RT = Rae+Raf;
Iaf = V/RT;
Vae = V-(Iaf*Raf);
Iae = Vae/Rx;
Iab = Iaf-Iae;
Vab = Rab*Iab;
Vbe = Vae-Vab;
Pbe = ((Vbe)^2)/(Ry);
Ibe = Vbe/Ry;
Ibc = Iab-Ibe;
Icde = (Ibc)/(2);
Vcd = Icde*(Rcd);
cat(Iaf,Pbe,Vcd);
